apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kafka
type: Opaque
stringData:
  POSTGRE_USER: ${POSTGRE_USER}
  POSTGRE_PASSWORD: ${POSTGRE_PASSWORD}
  POSTGRE_DB: ${POSTGRE_DB}