apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: quay.io/strimzi/kafka:0.38.0-kafka-3.6.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting consumer..."
          export KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap.kafka:9092
          export TOPIC_NAME=logs

          bin/kafka-console-consumer.sh --bootstrap-server $KAFKA_BOOTSTRAP_SERVERS --topic $TOPIC_NAME --from-beginning