apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginxdemos/hello:plain-text # To test in simplest way
        # image: nginxdemos/hello:non-existent-tag # To test Rollout failure
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: kafka
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80